services:
  mongo:
    image: docker.io/mongo:latest
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: docker.io/redis:latest
    expose:
      - 6379

  worker:
    build: .
    command: python3 celery_worker.py
    depends_on:
      - mongo
      - redis

  parser:
    build: .
    command: python3 main.py
    depends_on:
      - worker
